### ISSUE TITLE
Wrong order of configuration providers

### ISSUE THREAD

**Issue by marnilss** [Forestbrook/FunctionWithKeyVaultAndDI#1]
Hi
I've read your post https://www.forestbrook.net/docs/azure/functionwithkeyvaultanddi.html and highly appreciated it! Thank you!!!

But I've found an issue/problem with how Azure Functions work, and the way you add the configuration providers for appsettings.json files.
Nothing wrong really, but since the appsettings JSON configurations providers (configurationsource) are added after the ones provided by Azure Functions, they will override any value you specify in the application settings in the Azure portal for your Azure function.
You can also test it locally and see that, for any setting that has value both in appsettings.json and in local.settings.json, the last added providers (appsettings.json) wins.

If we compare that to appsettings.json and application settings on an Azure App Service, it is the other way around - the application settings "overrides" any setting in appsettings.json.

To solve it properly, we would need to change code in the Azure Functions framework, but I've come up with a workaround, which needs bo be invoked after adding the appsettings.json fileproviders, and before adding the KeyVault provider.

```
        private static void PrioritizeEnvironmentVariables(IFunctionsConfigurationBuilder builder)
        {
            var commandlineProvider = builder.ConfigurationBuilder.Sources.LastOrDefault(x => x is Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationSource);
            if (commandlineProvider != null)
            {
                builder.ConfigurationBuilder.Sources.Remove(commandlineProvider);
                builder.ConfigurationBuilder.Sources.Add(commandlineProvider);
            }
        }

```
I hope it was OK to add this feedback as an issue. I could not easily find another way to contact you.

Best regards
Marcus Nilsson

**Comment by Forestbrook** [comment]
Hi Marcus,

I don’t know why your application settings in the Azure portal for your Azure function are overridden by the settings in appsettings.json. This should not happen.

As you can see in Startup.cs in the method `ConfigureAppConfiguration()` `.AddEnvironmentVariables()` (which should load the Configuration application settings from the Azure portal) is added AFTER `.AddAppSettingsJson`, so the settings on the server should override the settings in appsettings.json.

To test all situations, I added 4 test settings and show them in the IsAliveFunction (see updated source code):
- in appsettings.json: TestSetting1, TestSetting2, TestSetting3, TestSetting4
- in appsettings.Development.json and appsettings.Production.json: TestSetting1
- on the server in Configuration application settings: TestSetting2
- in the KeyVault as Secret: TestSetting3
- in local.settings.json: TestSetting4

When I run locally http://localhost:7071/api/IsAliveFunction I get this result:

TestSetting1 = TestSetting1 from appsettings.Development.json
TestSetting2 = TestSetting2 from appsettings.json
TestSetting3 = TestSetting3 from KeyVault
TestSetting4 = TestSetting4 from local.settings.json

When run from the server I get this result:

TestSetting1 = TestSetting1 from appsettings.Production.json
TestSetting2 = TestSetting2 from server Configuration
TestSetting3 = TestSetting3 from KeyVault
TestSetting4 = TestSetting4 from appsettings.json

So TestSetting2 is correctly read from the server configuration, NOT from appsettings.json.

Please try this test code, to see whether this works correct for you or not.

Marcel.

**Comment by marnilss** [comment]
Hmm, I've been eating humble pie for breakfast 😳
Since I didn't copy your solution entirely, I only read some parts of your code thoroughly (functionhelper.cs), and was a little to quick on other parts.
So I did not see that you added another Environment-variables provider via `AddEnvironmentVariables()`.

Sorry that I caused you some work to prove me wrong.

Best regards,
Marcus Nilsson
